### ISSUE TITLE
compilation failed

### ISSUE THREAD

**Issue by dev4u** [shadowsocks/shadowsocks-rust#283]
i got same fail because of the commit https://github.com/shadowsocks/shadowsocks-rust/commit/b226d2a50d42044b0b9844c4f6b35c29bf5b4a61

```
error[E0308]: mismatched types
   --> src/relay/udprelay/association.rs:349:58
    |
349 |             context.local_flow_statistic().udp().incr_tx(send_len as u64);
    |                                                          ^^^^^^^^^^^^^^^ expected `usize`, found `u64`
    |
help: you can convert an `u64` to `usize` and panic if the converted value wouldn't fit
    |
349 |             context.local_flow_statistic().udp().incr_tx((send_len as u64).try_into().unwrap());
    |                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0308]: mismatched types
   --> src/relay/local.rs:179:30
    |
179 |         let buf: [u64; 2] = [tx, rx];
    |                              ^^ expected `u64`, found `usize`
    |
help: you can convert an `usize` to `u64` and panic if the converted value wouldn't fit
    |
179 |         let buf: [u64; 2] = [tx.try_into().unwrap(), rx];
    |                              ^^^^^^^^^^^^^^^^^^^^^^

error[E0308]: mismatched types
   --> src/relay/udprelay/association.rs:485:58
    |
485 |             context.local_flow_statistic().udp().incr_rx(recv_n as u64);
    |                                                          ^^^^^^^^^^^^^ expected `usize`, found `u64`
    |
help: you can convert an `u64` to `usize` and panic if the converted value wouldn't fit
    |
485 |             context.local_flow_statistic().udp().incr_rx((recv_n as u64).try_into().unwrap());
    |                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0308]: mismatched types
   --> src/relay/tcprelay/proxy_stream.rs:377:73
    |
377 |                     self.context().local_flow_statistic().tcp().incr_rx(n as u64);
    |                                                                         ^^^^^^^^ expected `usize`, found `u64`
    |
help: you can convert an `u64` to `usize` and panic if the converted value wouldn't fit
    |
377 |                     self.context().local_flow_statistic().tcp().incr_rx((n as u64).try_into().unwrap());
    |                                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0308]: mismatched types
   --> src/relay/tcprelay/proxy_stream.rs:395:73
    |
395 |                     self.context().local_flow_statistic().tcp().incr_tx(n as u64);
    |                                                                         ^^^^^^^^ expected `usize`, found `u64`
    |
help: you can convert an `u64` to `usize` and panic if the converted value wouldn't fit
    |
395 |                     self.context().local_flow_statistic().tcp().incr_tx((n as u64).try_into().unwrap());
    |                                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by zonyitoo** [comment]
Again... Is there any way to create a github action to compile in Android's environment?

**Comment by Mygod** [comment]
You can simply cross compile with android target?
