### ISSUE TITLE
1.23.5 does not compile with `aead-cipher` feature disabled

### ISSUE THREAD

**Issue by HanabishiRecca** [shadowsocks/shadowsocks-rust#1982]
I'm trying to build with such flags:
```
$ cargo build --release --bin ssservice --no-default-features --features 'service,logging,multi-threaded,aead-cipher-2022'
   Compiling shadowsocks-service v1.23.5 (/tmp/shadowsocks-rust/crates/shadowsocks-service)
error[E0308]: mismatched types
   --> crates/shadowsocks-service/src/manager/server.rs:482:43
    |
482 |             None => return Ok(AddResponse("method is required")),
    |                               ----------- ^^^^^^^^^^^^^^^^^^^^- help: try using a conversion method: `.to_string()`
    |                               |           |
    |                               |           expected `String`, found `&str`
    |                               arguments to this struct are incorrect
    |
note: tuple struct defined here
   --> /tmp/shadowsocks-rust/crates/shadowsocks/src/manager/protocol.rs:74:12
    |
74  | pub struct AddResponse(pub String);
    |            ^^^^^^^^^^^

For more information about this error, try `rustc --explain E0308`.
error: could not compile `shadowsocks-service` (lib) due to 1 previous error
```
Rust compiler is up to date:
```
$ rustc --version
rustc 1.88.0 (6b00bc388 2025-06-23) (Arch Linux rust 1:1.88.0-1)
```
Previous versions compiled just fine.

**Comment by HanabishiRecca** [comment]
It's due to `aead-cipher` feature not being enabled.
https://github.com/shadowsocks/shadowsocks-rust/blob/8f9419efa56d3b7db2b7d3cc0423b0bfd37565ea/crates/shadowsocks-service/src/manager/server.rs#L481-L482
I guess you forgot to test that condition.

**Comment by HanabishiRecca** [comment]
Apparently caused by #1968.

**Comment by AaronChen0** [comment]
`aead-cipher` is disabled in this commit https://github.com/shadowsocks/shadowsocks-rust/commit/01337d349c89189036f6b13b2bfc5184379ec32d, and becomes an optional feature. I think it should be specified in `README` and `RELEASE NOTE` to notify those building with `--no-default-features`.

**Comment by zonyitoo** [comment]
released shadowsocks-service v1.23.6.

**Comment by HanabishiRecca** [comment]
I don't think a lot of users are affected by it though, as most people build with default features.

Idk if there is a good way to test all possible configuration permutations without enumerating them manually, but I guess it would be good to at least add a test for `--no-default-features`.

**Comment by zonyitoo** [comment]
Test cases for shadowsocks-service were missing.
